### ISSUE TITLE
Pass network parse fuzzing for a week

### ISSUE THREAD

**Issue by nickbabcock** [nickbabcock/boxcars#11]
```
cargo +nightly fuzz run no-crc-body
```

Will crash almost instantly due to the abundance of unguarded, unchecked bitter statements. This means that anyone who sends in a slightly corrupted replay will see boxcars panic. Boxcars should never panic.

Boxcars doesn't panic when we don't have to parse the body:

```
cargo +nightly fuzz run no-crc-no-body
```

I'll close this issue once boxcars has been successfully fuzzed on `no-crc-body` for a week.

**Comment by tfausak** [comment]
Oh, fuzzing is another excellent benefit of Rust over Haskell! It's hard for Haskell to benefit from fuzzing because the garbage collector makes repeated runs different. 

In my opinion, taking the ~10% performance hit for checked reads (#8) is well worth it. That should make fuzzing crash less, right? Boxcars is already a couple orders of magnitude faster than Rattletrap. Finishing a couple more milliseconds faster isn't a big deal.

**Comment by nickbabcock** [comment]
> In my opinion, taking the ~10% performance hit for checked reads (#8) is well worth it. That should make fuzzing crash less, right? Boxcars is already a couple orders of magnitude faster than Rattletrap. Finishing a couple more milliseconds faster isn't a big deal.

That's true. I think potentially the best course of action would be for me to convert to checked reads, benchmark and if there is a hot path that can benefit from a guard + unchecked then do it.

**Comment by nickbabcock** [comment]
Completed and no crashes 🎉
