### ISSUE TITLE
Question:  Is this still actively maintained?

### ISSUE THREAD

**Issue by dtracers** [nickbabcock/boxcars#25]
Hi!

I am working on this project for replay parsing:
https://github.com/SaltieRL/carball

And we have been using rattletrap but are looking for something a bit faster.
So I was wondering if we could fork this into our org to work on it or if there was a way to reach you if we had questions as we worked on moving it over to our new version.
Also was wondering what the state of this was in terms of completeness in response compared to rattletrap.

**Comment by nickbabcock** [comment]
> And we have been using rattletrap but are looking for something a bit faster.

This is the right place.

>  Also was wondering what the state of this was in terms of completeness in response compared to rattletrap.

Everything that rattletrap parses, boxcars does too, but I last updated this for v1.50 (September 6th 2018). I'm assuming that in these last 7 months there has been an RL update that breaks the network / body format (as psyonix is wont to do). This is why the API allows one to skip parsing the network data if an error occurs and still be able to query the header data as that rarely changes.

To update to the latest RL version, I tend to follow the commits in rattletrap and port them over until I get a successfully parsed replay.

The JSON output between boxcars and rattletrap differs (and offhand I can't remember the differences), but they contain the same data so one should be able to translate between them (or bring boxcar's output more in line with rattletrap).

>  So I was wondering if we could fork this into our org to work on it

Certainly. From a legal standpoint there is nothing wrong with that.

Depending on your game plan, boxcars is also maintained as a [rust crate](https://crates.io/crates/boxcars). I'd like to avoid the situation where forked code is constantly improved and the crate gets left behind (but it's your prerogative). So changes from the fork can either be upstreamed here or I can grant additional ownership to the crate.

> or if there was a way to reach you if we had questions as we worked on moving it over to our new version.

I'm always around to help (even for questions like "why did you do x instead of y") and will respond if pinged 😄

**Comment by dtracers** [comment]
Sweet thanks for the response!

Our main goal is speeding up our network parsing as that is what use to get most of our stats.

Addionally we would be converting the network part to a byte array in the pandas format for repeated data (positions, orientation, controls)
And sending out json for non repeated data inside the network part (player names, events, other network metadata)

What is the best way to ping for questions?
For reference most of the work would be going on in here https://discord.gg/c8cArY9

**Comment by nickbabcock** [comment]
Ok updated to support v1.59 replays, so I'll close this issue as it's a bit open ended. Let me know about additional trials / tribulations through discord mentions or github issues 😄
