### ISSUE TITLE
Boxcars fails to parse a 1.66 RL Replay

### ISSUE THREAD

**Issue by levelonedev** [nickbabcock/boxcars#52]
I tried applying jjbot's fix to his parser(https://github.com/jjbott/RocketLeagueReplayParser/commit/81c09f3004e62556afe939bf601265f8e611a169#diff-0c02ca5dbc85c6f2a5d0987bcd952c04) by adding an entry to `OBJECT_CLASSES` similar to how he did. But this still fails to parse after adding it.

```       
 .entry("ProjectX.Default__NetModeReplicator_X", "\"ProjectX.NetModeReplicator_X\"")
```

Here is a replay that breaks master.

[21A81.zip](https://github.com/nickbabcock/boxcars/files/3563264/21A81.zip)

**Comment by nickbabcock** [comment]
jjbott is a good guide to know what has changed, but rattletrap is more inline with how boxcars is structured. The gist of the difference is that jjbott's assumes the object hierarchy found in the replay is mostly correct and patches only some of the entries whereas rattletrap (and boxcars) construct the hierarchy the same way regardless of replay. When rattletrap doesn't have the fix applied I play around to get a better feel where the problem is. For instance, the replay that you uploaded fails with the following message:

> Time was out of range. Backtracking from frame: 1 to 0, the last actor (15) had a name id of Some(15), object id: 299 (ProjectX.Default__NetModeReplicator_X), and trajectory: Trajectory { location: None, rotation: None }. This may mean that a new update of Rocket League updated this object.

Based on the error message I guessed that `ProjectX.Default__NetModeReplicator_X` should have a location -- and I guess correctly. The uploaded replay now passes.
