### ISSUE TITLE
How to use this parser

### ISSUE THREAD

**Issue by jball1997** [nickbabcock/boxcars#85]
Hi, I am wondering if this parser is working. Also, I cannot figure out how to use it. Any help is appreciated.

**Comment by nickbabcock** [comment]
How would you like to parse rocket league replays?

- From within a programming language: boxcars is the right spot
- From the command line / terminal: [Use the latest rrrocket release](https://github.com/nickbabcock/rrrocket/releases/latest) (built on boxcars)
- From a website: https://rl.nickb.dev/ (built on boxcars)

**Comment by jball1997** [comment]
Thanks. I'm going to go with rrrocket. My next question has to do with the JSON output. Is there a legend/key so that I can more easily understand the output and what it means? For instance, I'm wanting to save car/ball positions, velocities, etc. Thanks again for the help.

**Comment by nickbabcock** [comment]
Let me just prefix this by saying I'm not an expert in the nuances in how to interpret some of the replay structure. The teams behind Calculated.gg and gif your games would be more knowledgeable, but I'll let you know what I would do.

Car / ball positions, velocities, and rotations will be in the network data. So you'll need to run `rrrocket` with `-n` or `--network-parse`.

Inside of the JSON data, you'll find `network_frames` and `frames` inside of that. The first thing you'll want to do is find where the car and ball actors are created in the `new_actors` of a frame:

```json
"network_frames": {
  "frames": [
    {
      "time": 24.67961,
      "delta": 0.01668344,
      "new_actors": [
        {
          "actor_id": 0,
          "name_id": 0,
          "object_id": 29,
        },
```

Here we see the creation of an actor with an object_id of 29. Look up the object name by examining the 29th entry in the `objects` array. For me, I do `./rrrocket my.replay | jq '.objects[29]'`. The result:

```
"Archetypes.CarComponents.CarComponent_Dodge"
```

Hmm not quite what we're looking for. You may have better luck scanning the objects array for the object name you're looking for and taking note of it's index. "Archetypes.Ball.Ball_Default" stands out to me. Checking for it's index:

```
./rrrocket my.replay | jq '.objects | to_entries | .[] | select(.value == "Archetypes.Ball.Ball_Default")'
```

The result:

```
{
  "key": 80,
  "value": "Archetypes.Ball.Ball_Default"
}
```

So now go back to the network data and find all the new actors with a object_id of 80

```
./rrrocket -n my.replay | jq '.network_frames.frames[].new_actors[] | select(.object_id == 80)'
```

Disappointingly there may be no results. This is because there can be many types of balls. A cheat sheet of ball types:

https://github.com/SaltieRL/carball/blob/7461f79185afa7eed43f8c67fac1c677603480e3/carball/json_parser/actor/ball.py#L5-L11

Since I was testing on a breakout replay, the "Archetypes.Ball.Ball_Breakout" returned a hit in the objects array (85). Searching for this yielded several entries like:

```json
{
  "actor_id": 62,
  "name_id": 296,
  "object_id": 85,
  "initial_trajectory": {
    "location": {
      "bias": 4096,
      "dx": 4315,
      "dy": 1085,
      "dz": 3894
    },
    "rotation": {
      "yaw": 6,
      "pitch": 88,
      "roll": -101
    }
  }
}
```

There you see location and rotation data. The raw formula for calculating x,y,z from dx, dy, dz, and bias is:

```
x = dx - bias
y = dy - bias
z = dz - bias
```

So:

```json
"location": {
  "bias": 4096,
  "dx": 6048,
  "dy": 1632,
  "dz": 4113
},
```

Would translate into

```
x: 1952
y: -2464
z: 17
```

Now that we know where the ball starts and how it is facing, we need to find out how it moves. For this, we'll take advantage of the `actor_id` of 62 and look for all updates:

```
./rrrocket -n my.replay | jq '.network_frames.frames[].updated_actors[] | select(.actor_id == 62).attribute.RigidBody | select(. != null)'
```

Due note that actor ids can be recycled! There is a `deleted_actor` array that is important to keep track of.

The output of the above command can include many lines of:

```json
{
  "sleeping": false,
  "location": {
    "bias": 4096,
    "dx": 4226,
    "dy": 1092,
    "dz": 3944
  },
  "x": 215,
  "y": 23467,
  "z": 40705,
  "linear_velocity": {
    "bias": 16384,
    "dx": 25148,
    "dy": 15711,
    "dz": 11837
  },
  "angular_velocity": {
    "bias": 2048,
    "dx": 2635,
    "dy": 3654,
    "dz": 1367
  }
}
```

Now this is where my knowledge gets shaky. With the new location, linear velocity, angular velocity, and (I believe) quaternion, one should be able to accurately track the ball.

Phew! That's just for the ball. Cars are similar. They are created and then have their rigidbody updated. Psyonix didn't make it easy on us :laughing:

If you come across anything that'd make it easier to work with the data / json / etc, I'm happy to add it to the repo.

**Comment by jball1997** [comment]
You're awesome! Thanks for helping. I will work on this and try to develop a way to keep track of player and ball locations, velocities, and rotation throughout a replay.

**Comment by nickbabcock** [comment]
Excellent, good luck! 🍀
